// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "dc08532f-4928-47a9-8544-019f33a8d3b8";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRemoteControlChange();
void onSelectChargingCurrentChange();

bool remoteControl;
float displayVrms;
float displayFreq;
float selectChargingCurrent;
float displayPWMDutyCycle;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(remoteControl, READWRITE, ON_CHANGE, onRemoteControlChange);
  ArduinoCloud.addProperty(displayVrms, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(displayFreq, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(selectChargingCurrent, READWRITE, ON_CHANGE, onSelectChargingCurrentChange);
  ArduinoCloud.addProperty(displayPWMDutyCycle, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
